make chnages and add docker file

diff --git a/journalApp/Jenkinsfile b/journalApp/Jenkinsfile
--- a/journalApp/Jenkinsfile
+++ b/journalApp/Jenkinsfile
@@ -1,5 +1,50 @@
+// pipeline {
+//     agent any
+
+//     stages {
+
+//         stage('Checkout') {
+//             steps {
+//                 checkout scm
+//             }
+//         }
+
+//         stage('Build') {
+//             steps {
+//                 dir('journalApp') {
+//                     sh 'chmod +x mvnw'
+//                     sh './mvnw clean package -DskipTests'
+//                 }
+//             }
+//         }
+
+//         stage('Verify JAR') {
+//             steps {
+//                 dir('journalApp') {
+//                     sh 'ls -lh target'
+//                 }
+//             }
+//         }
+//     }
+
+//     post {
+//         success {
+//             echo 'Build Successful'
+//         }
+
+//         failure {
+//             echo 'Build Failed'
+//         }
+//     }
+// }
+
 pipeline {
     agent any
+
+    environment {
+        IMAGE_NAME = "journal-app"
+        CONTAINER_NAME = "journal-app-container"
+    }
 
     stages {
 
@@ -9,7 +54,7 @@ pipeline {
             }
         }
 
-        stage('Build') {
+        stage('Build Application') {
             steps {
                 dir('journalApp') {
                     sh 'chmod +x mvnw'
@@ -18,22 +63,62 @@ pipeline {
             }
         }
 
-        stage('Verify JAR') {
+        stage('Verify Build') {
             steps {
                 dir('journalApp') {
                     sh 'ls -lh target'
                 }
             }
         }
+
+        stage('Build Docker Image') {
+            steps {
+                dir('journalApp') {
+                    sh 'docker build -t ${IMAGE_NAME}:latest .'
+                }
+            }
+        }
+
+        stage('Stop Old Container') {
+            steps {
+                sh '''
+                docker stop ${CONTAINER_NAME} || true
+                docker rm ${CONTAINER_NAME} || true
+                '''
+            }
+        }
+
+        stage('Run Container') {
+            steps {
+                sh '''
+                docker run -d \
+                --name ${CONTAINER_NAME} \
+                -p 8081:8080 \
+                ${IMAGE_NAME}:latest
+                '''
+            }
+        }
+
+        stage('Health Check') {
+            steps {
+                sh 'sleep 20'
+                sh 'curl http://host.docker.internal:8081'
+            }
+        }
     }
 
     post {
+
         success {
-            echo 'Build Successful'
+
+            echo 'Application deployed successfully'
+
         }
 
         failure {
-            echo 'Build Failed'
+
+            echo 'Deployment failed'
+
         }
     }
 }
